[package]
name = "rustwell"
version = "0.3.0"
edition = "2024"
license = "MIT"
description = "A library for parsing and compiling fountain screenplay scripts."
repository = "https://github.com/frblo/rustwell"
keywords = ["fountain", "screenplay", "stageplay"]
categories = ["parser-implementations"]

[lib]
path = "src/lib.rs"

[dependencies]
bitflags = "2"
krilla = "0.7.0"
unicode-properties = "0.1.4"
